[project]
name = "runelite-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "py4j>=0.10.9.7",
    "torch>=2.4.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
