import typing
from typing import Any, List, Dict, Set, Optional, Tuple, Iterable, Collection

class Actor:
    def __init__(self, java_instance: Any) -> None: ...
    def getWorldView(self) -> 'WorldView': ...
    def getCombatLevel(self) -> int: ...
    def getName(self) -> str: ...
    def isInteracting(self) -> bool: ...
    def getInteracting(self) -> 'Actor': ...
    def getHealthRatio(self) -> int: ...
    def getHealthScale(self) -> int: ...
    def getWorldLocation(self) -> 'WorldPoint': ...
    def getLocalLocation(self) -> 'LocalPoint': ...
    def getOrientation(self) -> int: ...
    def getCurrentOrientation(self) -> int: ...
    def getAnimation(self) -> int: ...
    def getPoseAnimation(self) -> int: ...
    def setPoseAnimation(self, animation: int) -> None: ...
    def getPoseAnimationFrame(self) -> int: ...
    def setPoseAnimationFrame(self, frame: int) -> None: ...
    def getIdlePoseAnimation(self) -> int: ...
    def setIdlePoseAnimation(self, animation: int) -> None: ...
    def getIdleRotateLeft(self) -> int: ...
    def setIdleRotateLeft(self, animationID: int) -> None: ...
    def getIdleRotateRight(self) -> int: ...
    def setIdleRotateRight(self, animationID: int) -> None: ...
    def getWalkAnimation(self) -> int: ...
    def setWalkAnimation(self, animationID: int) -> None: ...
    def getWalkRotateLeft(self) -> int: ...
    def setWalkRotateLeft(self, animationID: int) -> None: ...
    def getWalkRotateRight(self) -> int: ...
    def setWalkRotateRight(self, animationID: int) -> None: ...
    def getWalkRotate180(self) -> int: ...
    def setWalkRotate180(self, animationID: int) -> None: ...
    def getRunAnimation(self) -> int: ...
    def setRunAnimation(self, animationID: int) -> None: ...
    def setAnimation(self, animation: int) -> None: ...
    def getAnimationFrame(self) -> int: ...
    def setActionFrame(self, frame: int) -> None: ...
    def setAnimationFrame(self, frame: int) -> None: ...
    def getSpotAnims(self) -> 'IterableHashTable': ...
    def hasSpotAnim(self, spotAnimId: int) -> bool: ...
    def createSpotAnim(self, id_: int, spotAnimId: int, height: int, delay: int) -> None: ...
    def removeSpotAnim(self, id_: int) -> None: ...
    def clearSpotAnims(self) -> None: ...
    def getGraphic(self) -> int: ...
    def setGraphic(self, graphic: int) -> None: ...
    def getGraphicHeight(self) -> int: ...
    def setGraphicHeight(self, height: int) -> None: ...
    def getSpotAnimFrame(self) -> int: ...
    def setSpotAnimFrame(self, spotAnimFrame: int) -> None: ...
    def getCanvasTilePoly(self) -> 'Polygon': ...
    def getCanvasTextLocation(self, graphics: 'Graphics2D', text: str, heightOffset: int) -> 'Point': ...
    def getCanvasImageLocation(self, image: 'BufferedImage', heightOffset: int) -> 'Point': ...
    def getCanvasSpriteLocation(self, sprite: 'SpritePixels', heightOffset: int) -> 'Point': ...
    def getMinimapLocation(self) -> 'Point': ...
    def getLogicalHeight(self) -> int: ...
    def getConvexHull(self) -> 'Shape': ...
    def getWorldArea(self) -> 'WorldArea': ...
    def getOverheadText(self) -> str: ...
    def setOverheadText(self, overheadText: str) -> None: ...
    def getOverheadCycle(self) -> int: ...
    def setOverheadCycle(self, cycles: int) -> None: ...
    def isDead(self) -> bool: ...
    def setDead(self, dead: bool) -> None: ...
    def getFootprintSize(self) -> int: ...
    def getAnimationHeightOffset(self) -> int: ...
