import typing
from typing import Any, List, Dict, Set, Optional, Tuple, Iterable, Collection

class ChatLineBuffer:
    def __init__(self, java_instance: Any) -> None: ...
    def getLines(self) -> typing.List['MessageNode']: ...
    def getLength(self) -> int: ...
    def removeMessageNode(self, node: 'MessageNode') -> None: ...
