import typing
from typing import Any, List, Dict, Set, Optional, Tuple, Iterable, Collection

class Client:
    def __init__(self, java_instance: Any) -> None: ...
    def getCallbacks(self) -> 'Callbacks': ...
    def getDrawCallbacks(self) -> 'DrawCallbacks': ...
    def setDrawCallbacks(self, drawCallbacks: 'DrawCallbacks') -> None: ...
    def getBuildID(self) -> str: ...
    def getEnvironment(self) -> int: ...
    def getBoostedSkillLevel(self, skill: 'Skill') -> int: ...
    def getRealSkillLevel(self, skill: 'Skill') -> int: ...
    def getTotalLevel(self) -> int: ...
    def addChatMessage(self, type: 'ChatMessageType', name: str, message: str, sender: str) -> 'MessageNode': ...
    def getGameState(self) -> 'GameState': ...
    def setGameState(self, gameState: 'GameState') -> None: ...
    def stopNow(self) -> None: ...
    def getLauncherDisplayName(self) -> str: ...
    def getUsername(self) -> str: ...
    def setUsername(self, name: str) -> None: ...
    def setPassword(self, password: str) -> None: ...
    def setOtp(self, otp: str) -> None: ...
    def getCurrentLoginField(self) -> int: ...
    def getLoginIndex(self) -> int: ...
    def getAccountType(self) -> 'AccountType': ...
    def getCanvas(self) -> 'Canvas': ...
    def getFPS(self) -> int: ...
    def getCameraX(self) -> int: ...
    def getCameraFpX(self) -> float: ...
    def getCameraY(self) -> int: ...
    def getCameraFpY(self) -> float: ...
    def getCameraZ(self) -> int: ...
    def getCameraFpZ(self) -> float: ...
    def getCameraPitch(self) -> int: ...
    def getCameraFpPitch(self) -> float: ...
    def getCameraYaw(self) -> int: ...
    def getCameraFpYaw(self) -> float: ...
    def getWorld(self) -> int: ...
    def getCanvasHeight(self) -> int: ...
    def getCanvasWidth(self) -> int: ...
    def getViewportHeight(self) -> int: ...
    def getViewportWidth(self) -> int: ...
    def getViewportXOffset(self) -> int: ...
    def getViewportYOffset(self) -> int: ...
    def getScale(self) -> int: ...
    def getMouseCanvasPosition(self) -> 'Point': ...
    def getLocalPlayer(self) -> 'Player': ...
    def getFollower(self) -> 'NPC': ...
    def getItemDefinition(self, id_: int) -> 'ItemComposition': ...
    def getItemModelCache(self) -> 'NodeCache': ...
    def getItemSpriteCache(self) -> 'NodeCache': ...
    def getSprites(self, source: 'IndexDataBase', archiveId: int, fileId: int) -> typing.List['SpritePixels']: ...
    def getIndexSprites(self) -> 'IndexDataBase': ...
    def getIndexScripts(self) -> 'IndexDataBase': ...
    def getIndexConfig(self) -> 'IndexDataBase': ...
    def getIndex(self, id_: int) -> 'IndexDataBase': ...
    def getMouseCurrentButton(self) -> int: ...
    def isDraggingWidget(self) -> bool: ...
    def getDraggedWidget(self) -> 'Widget': ...
    def getDraggedOnWidget(self) -> 'Widget': ...
    def setDraggedOnWidget(self, widget: 'Widget') -> None: ...
    def getDragTime(self) -> int: ...
    def getTopLevelInterfaceId(self) -> int: ...
    def getWidgetRoots(self) -> typing.List['Widget']: ...
    def getWidget(self, widget: 'WidgetInfo') -> 'Widget': ...
    def getWidgetPositionsX(self) -> typing.List[int]: ...
    def getWidgetPositionsY(self) -> typing.List[int]: ...
    def getEnergy(self) -> int: ...
    def getWeight(self) -> int: ...
    def getPlayerOptions(self) -> typing.List[str]: ...
    def getPlayerOptionsPriorities(self) -> typing.List[bool]: ...
    def getPlayerMenuTypes(self) -> typing.List[int]: ...
    def getWorldList(self) -> typing.List['World']: ...
    def getMenu(self) -> 'Menu': ...
    def createMenuEntry(self, idx: int) -> 'MenuEntry': ...
    def getMenuEntries(self) -> typing.List['MenuEntry']: ...
    def setMenuEntries(self, entries: 'MenuEntry[]') -> None: ...
    def isMenuOpen(self) -> bool: ...
    def isMenuScrollable(self) -> bool: ...
    def getMenuScroll(self) -> int: ...
    def setMenuScroll(self, scroll: int) -> None: ...
    def getMenuX(self) -> int: ...
    def getMenuY(self) -> int: ...
    def getMenuHeight(self) -> int: ...
    def getMenuWidth(self) -> int: ...
    def getMapAngle(self) -> int: ...
    def isResized(self) -> bool: ...
    def getRevision(self) -> int: ...
    def getVarps(self) -> typing.List[int]: ...
    def getServerVarps(self) -> typing.List[int]: ...
    def getVarcMap(self) -> 'Object>': ...
    def getVar(self, varbit: int) -> int: ...
    def getVarbitValue(self, varbit: int) -> int: ...
    def getServerVarbitValue(self, varbit: int) -> int: ...
    def getVarpValue(self, varpId: int) -> int: ...
    def getServerVarpValue(self, varpId: int) -> int: ...
    def getVarcIntValue(self, var: int) -> int: ...
    def getVarcStrValue(self, var: int) -> str: ...
    def setVarcStrValue(self, var: int, value: str) -> None: ...
    def setVarcIntValue(self, var: int, value: int) -> None: ...
    def setVarbit(self, varbit: int, value: int) -> None: ...
    def getVarbit(self, id_: int) -> 'VarbitComposition': ...
    def setVarbitValue(self, varps: 'int[]', varbit: int, value: int) -> None: ...
    def queueChangedVarp(self, varp: int) -> None: ...
    def closeInterface(self, interfaceNode: 'WidgetNode', unload: bool) -> None: ...
    def getWidgetFlags(self) -> 'HashTable': ...
    def getWidgetConfig(self, w: 'Widget') -> 'WidgetConfigNode': ...
    def getComponentTable(self) -> 'HashTable': ...
    def getGrandExchangeOffers(self) -> typing.List['GrandExchangeOffer']: ...
    def isPrayerActive(self, prayer: 'Prayer') -> bool: ...
    def getSkillExperience(self, skill: 'Skill') -> int: ...
    def getOverallExperience(self) -> int: ...
    def refreshChat(self) -> None: ...
    def getChatLineMap(self) -> 'ChatLineBuffer>': ...
    def getMessages(self) -> 'IterableHashTable': ...
    def getObjectDefinition(self, objectId: int) -> 'ObjectComposition': ...
    def getNpcDefinition(self, npcId: int) -> 'NPCComposition': ...
    def getStructComposition(self, structID: int) -> 'StructComposition': ...
    def getStructCompositionCache(self) -> 'NodeCache': ...
    def getDBTableField(self, rowID: int, column: int, tupleIndex: int) -> typing.List[typing.Any]: ...
    def getDBRowConfig(self, rowID: int) -> 'DBRowConfig': ...
    def getDBRowsByValue(self, table: int, column: int, tupleIndex: int, value: typing.Any) -> typing.List['Integer']: ...
    def getDBTableRows(self, table: int) -> typing.List['Integer']: ...
    def getMapElementConfig(self, id_: int) -> 'MapElementConfig': ...
    def getMapScene(self) -> typing.List['IndexedSprite']: ...
    def getMapDots(self) -> typing.List['SpritePixels']: ...
    def getGameCycle(self) -> int: ...
    def getMapIcons(self) -> typing.List['SpritePixels']: ...
    def getModIcons(self) -> typing.List['IndexedSprite']: ...
    def setModIcons(self, modIcons: 'IndexedSprite[]') -> None: ...
    def createIndexedSprite(self) -> 'IndexedSprite': ...
    def createSpritePixels(self, pixels: 'int[]', width: int, height: int) -> 'SpritePixels': ...
    def getLocalDestinationLocation(self) -> 'LocalPoint': ...
    def createRuneLiteObject(self) -> 'RuneLiteObject': ...
    def registerRuneLiteObject(self, controller: 'RuneLiteObjectController') -> None: ...
    def removeRuneLiteObject(self, controller: 'RuneLiteObjectController') -> None: ...
    def isRuneLiteObjectRegistered(self, controller: 'RuneLiteObjectController') -> bool: ...
    def loadModelData(self, id_: int) -> 'ModelData': ...
    def mergeModels(self, models: 'ModelData[]', length: int) -> 'ModelData': ...
    def loadModel(self, id_: int) -> 'Model': ...
    def loadAnimation(self, id_: int) -> 'Animation': ...
    def getMusicVolume(self) -> int: ...
    def setMusicVolume(self, volume: int) -> None: ...
    def playSoundEffect(self, id_: int) -> None: ...
    def getActiveMidiRequests(self) -> typing.List['MidiRequest']: ...
    def getBufferProvider(self) -> 'BufferProvider': ...
    def getMouseIdleTicks(self) -> int: ...
    def getMouseLastPressedMillis(self) -> int: ...
    def getKeyboardIdleTicks(self) -> int: ...
    def changeMemoryMode(self, lowMemory: bool) -> None: ...
    def getItemContainer(self, inventory: 'InventoryID') -> 'ItemContainer': ...
    def getItemContainers(self) -> 'HashTable': ...
    def getIntStackSize(self) -> int: ...
    def setIntStackSize(self, stackSize: int) -> None: ...
    def getIntStack(self) -> typing.List[int]: ...
    def getObjectStackSize(self) -> int: ...
    def setObjectStackSize(self, stackSize: int) -> None: ...
    def getObjectStack(self) -> typing.List[typing.Any]: ...
    def getArraySizes(self, arrayId: int) -> int: ...
    def getArray(self, arrayId: int) -> typing.List[int]: ...
    def getScriptActiveWidget(self) -> 'Widget': ...
    def getScriptDotWidget(self) -> 'Widget': ...
    def isFriended(self, name: str, mustBeLoggedIn: bool) -> bool: ...
    def getFriendsChatManager(self) -> 'FriendsChatManager': ...
    def getFriendContainer(self) -> 'FriendContainer': ...
    def getIgnoreContainer(self) -> 'NameableContainer': ...
    def getPreferences(self) -> 'Preferences': ...
    def getCameraYawTarget(self) -> int: ...
    def getCameraPitchTarget(self) -> int: ...
    def setCameraYawTarget(self, cameraYawTarget: int) -> None: ...
    def setCameraPitchTarget(self, cameraPitchTarget: int) -> None: ...
    def setCameraSpeed(self, speed: float) -> None: ...
    def setCameraMouseButtonMask(self, mask: int) -> None: ...
    def setCameraPitchRelaxerEnabled(self, enabled: bool) -> None: ...
    def setInvertYaw(self, invertYaw: bool) -> None: ...
    def setInvertPitch(self, invertPitch: bool) -> None: ...
    def getRenderOverview(self) -> 'RenderOverview': ...
    def getWorldMap(self) -> 'WorldMap': ...
    def isStretchedEnabled(self) -> bool: ...
    def setStretchedEnabled(self, state: bool) -> None: ...
    def isStretchedFast(self) -> bool: ...
    def setStretchedFast(self, state: bool) -> None: ...
    def setStretchedIntegerScaling(self, state: bool) -> None: ...
    def setStretchedKeepAspectRatio(self, state: bool) -> None: ...
    def setScalingFactor(self, factor: int) -> None: ...
    def invalidateStretching(self, resize: bool) -> None: ...
    def getStretchedDimensions(self) -> 'Dimension': ...
    def getRealDimensions(self) -> 'Dimension': ...
    def changeWorld(self, world: 'World') -> None: ...
    def createWorld(self) -> 'World': ...
    def drawInstanceMap(self, z: int) -> 'SpritePixels': ...
    def runScript(self, args: 'Object...') -> None: ...
    def createScriptEvent(self, ...args: typing.Any) -> 'ScriptEvent': ...
    def hasHintArrow(self) -> bool: ...
    def getHintArrowType(self) -> int: ...
    def clearHintArrow(self) -> None: ...
    def setHintArrow(self, point: 'WorldPoint') -> None: ...
    def getHintArrowPoint(self) -> 'WorldPoint': ...
    def getHintArrowPlayer(self) -> 'Player': ...
    def getHintArrowNpc(self) -> 'NPC': ...
    def getAnimationInterpolationFilter(self) -> 'IntPredicate': ...
    def setAnimationInterpolationFilter(self, filter: 'IntPredicate') -> None: ...
    def getBoostedSkillLevels(self) -> typing.List[int]: ...
    def getRealSkillLevels(self) -> typing.List[int]: ...
    def getSkillExperiences(self) -> typing.List[int]: ...
    def queueChangedSkill(self, skill: 'Skill') -> None: ...
    def getSpriteOverrides(self) -> 'SpritePixels>': ...
    def getWidgetSpriteOverrides(self) -> 'SpritePixels>': ...
    def setCompass(self, spritePixels: 'SpritePixels') -> None: ...
    def getWidgetSpriteCache(self) -> 'NodeCache': ...
    def getTickCount(self) -> int: ...
    def setTickCount(self, tickCount: int) -> None: ...
    def setInventoryDragDelay(self, delay: int) -> None: ...
    def getWorldHost(self) -> str: ...
    def getWorldType(self) -> 'EnumSet': ...
    def getCameraMode(self) -> int: ...
    def setCameraMode(self, mode: int) -> None: ...
    def getCameraFocalPointX(self) -> float: ...
    def setCameraFocalPointX(self, x: float) -> None: ...
    def getCameraFocalPointY(self) -> float: ...
    def setCameraFocalPointY(self, y: float) -> None: ...
    def getCameraFocalPointZ(self) -> float: ...
    def setCameraFocalPointZ(self, z: float) -> None: ...
    def setFreeCameraSpeed(self, speed: int) -> None: ...
    def getOculusOrbState(self) -> int: ...
    def setOculusOrbState(self, state: int) -> None: ...
    def setOculusOrbNormalSpeed(self, speed: int) -> None: ...
    def getOculusOrbFocalPointX(self) -> int: ...
    def getOculusOrbFocalPointY(self) -> int: ...
    def openWorldHopper(self) -> None: ...
    def hopToWorld(self, world: 'World') -> None: ...
    def setSkyboxColor(self, skyboxColor: int) -> None: ...
    def getSkyboxColor(self) -> int: ...
    def isGpu(self) -> bool: ...
    def setGpuFlags(self, gpuflags: int) -> None: ...
    def setExpandedMapLoading(self, chunks: int) -> None: ...
    def getExpandedMapLoading(self) -> int: ...
    def get3dZoom(self) -> int: ...
    def getCenterX(self) -> int: ...
    def getCenterY(self) -> int: ...
    def getTextureProvider(self) -> 'TextureProvider': ...
    def getRasterizer3D_clipMidX2(self) -> int: ...
    def getRasterizer3D_clipNegativeMidX(self) -> int: ...
    def getRasterizer3D_clipNegativeMidY(self) -> int: ...
    def getRasterizer3D_clipMidY2(self) -> int: ...
    def checkClickbox(self, projection: 'Projection', model: 'Model', orientation: int, x: int, y: int, z: int, hash: int) -> None: ...
    def isWidgetSelected(self) -> bool: ...
    def setWidgetSelected(self, selected: bool) -> None: ...
    def getSelectedWidget(self) -> 'Widget': ...
    def getFocusedInputFieldWidget(self) -> 'Widget': ...
    def getItemCompositionCache(self) -> 'NodeCache': ...
    def getObjectCompositionCache(self) -> 'NodeCache': ...
    def getAnimationCache(self) -> 'NodeCache': ...
    def getCrossSprites(self) -> typing.List['SpritePixels']: ...
    def getEnum(self, id_: int) -> 'EnumComposition': ...
    def draw2010Menu(self, alpha: int) -> None: ...
    def drawOriginalMenu(self, alpha: int) -> None: ...
    def resetHealthBarCaches(self) -> None: ...
    def getItemCount(self) -> int: ...
    def setAllWidgetsAreOpTargetable(self, value: bool) -> None: ...
    def setGeSearchResultCount(self, count: int) -> None: ...
    def setGeSearchResultIds(self, ids: 'short[]') -> None: ...
    def setGeSearchResultIndex(self, index: int) -> None: ...
    def setLoginScreen(self, pixels: 'SpritePixels') -> None: ...
    def setShouldRenderLoginScreenFire(self, val: bool) -> None: ...
    def getCrossWorldMessageIds(self) -> typing.List[int]: ...
    def getCrossWorldMessageIdsIndex(self) -> int: ...
    def getClanChannel(self) -> 'ClanChannel': ...
    def getGuestClanChannel(self) -> 'ClanChannel': ...
    def getClanSettings(self) -> 'ClanSettings': ...
    def getGuestClanSettings(self) -> 'ClanSettings': ...
    def setUnlockedFps(self, unlock: bool) -> None: ...
    def setUnlockedFpsTarget(self, fps: int) -> None: ...
    def getAmbientSoundEffects(self) -> 'Deque': ...
    def setIdleTimeout(self, ticks: int) -> None: ...
    def getIdleTimeout(self) -> int: ...
    def isMinimapZoom(self) -> bool: ...
    def setMinimapZoom(self, minimapZoom: bool) -> None: ...
    def getMinimapZoom(self) -> float: ...
    def setMinimapTileDrawer(self, drawTile: 'TileFunction') -> None: ...
    def getRasterizer(self) -> 'Rasterizer': ...
    def menuAction(self, p0: int, p1: int, action: 'MenuAction', id_: int, itemId: int, option: str, target: str) -> None: ...
    def getWorldView(self, id_: int) -> 'WorldView': ...
    def getTopLevelWorldView(self) -> 'WorldView': ...
    def isCameraShakeDisabled(self) -> bool: ...
    def setCameraShakeDisabled(self, disabled: bool) -> None: ...
    def getDraw2DMask(self) -> int: ...
    def getInstanceTemplateChunks(self) -> typing.List['int[][]']: ...
    def getXteaKeys(self) -> typing.List['int[]']: ...
    def isInInstancedRegion(self) -> bool: ...
    def getMapRegions(self) -> typing.List[int]: ...
    def getScene(self) -> 'Scene': ...
    def getPlayers(self) -> typing.List['Player']: ...
    def getNpcs(self) -> typing.List['NPC']: ...
    def getCollisionMaps(self) -> typing.List['CollisionData']: ...
    def getPlane(self) -> int: ...
    def getTileHeights(self) -> typing.List['int[][]']: ...
    def getTileSettings(self) -> typing.List['byte[][]']: ...
    def getBaseX(self) -> int: ...
    def getBaseY(self) -> int: ...
    def createProjectile(self, id_: int, plane: int, startX: int, startY: int, startZ: int, startCycle: int, endCycle: int, slope: int, startHeight: int, endHeight: int, target: 'Actor', targetX: int, targetY: int) -> 'Projectile': ...
    def getProjectiles(self) -> 'Deque': ...
    def getGraphicsObjects(self) -> 'Deque': ...
    def getSelectedSceneTile(self) -> 'Tile': ...
    def applyTransformations(self, model: 'Model', animA: 'Animation', frameA: int, animB: 'Animation', frameB: int) -> 'Model': ...
    def createSceneTilePaint(self, swColor: int, seColor: int, neColor: int, nwColor: int, texture: int, minimapRgb: int, flatShade: bool) -> 'SceneTilePaint': ...
    def getCameraFocusEntity(self) -> 'CameraFocusableEntity': ...
    def findWorldViewFromWorldPoint(self, point: 'WorldPoint') -> 'WorldView': ...
    def getSocketFD(self) -> 'FileDescriptor': ...
