import typing
from typing import Any, List, Dict, Set, Optional, Tuple, Iterable, Collection

class GrandExchangeOffer:
    def __init__(self, java_instance: Any) -> None: ...
    def getQuantitySold(self) -> int: ...
    def getItemId(self) -> int: ...
    def getTotalQuantity(self) -> int: ...
    def getPrice(self) -> int: ...
    def getSpent(self) -> int: ...
    def getState(self) -> 'GrandExchangeOfferState': ...
