import typing
from typing import Any, List, Dict, Set, Optional, Tuple, Iterable, Collection

class MenuEntry:
    def __init__(self, java_instance: Any) -> None: ...
    def getOption(self) -> str: ...
    def setOption(self, option: str) -> 'MenuEntry': ...
    def getTarget(self) -> str: ...
    def setTarget(self, target: str) -> 'MenuEntry': ...
    def getIdentifier(self) -> int: ...
    def setIdentifier(self, identifier: int) -> 'MenuEntry': ...
    def getType(self) -> 'MenuAction': ...
    def setType(self, type: 'MenuAction') -> 'MenuEntry': ...
    def getParam0(self) -> int: ...
    def setParam0(self, param0: int) -> 'MenuEntry': ...
    def getParam1(self) -> int: ...
    def setParam1(self, param1: int) -> 'MenuEntry': ...
    def isForceLeftClick(self) -> bool: ...
    def setForceLeftClick(self, forceLeftClick: bool) -> 'MenuEntry': ...
    def getWorldViewId(self) -> int: ...
    def setWorldViewId(self, worldViewId: int) -> 'MenuEntry': ...
    def isDeprioritized(self) -> bool: ...
    def setDeprioritized(self, deprioritized: bool) -> 'MenuEntry': ...
    def onClick(self, callback: 'Consumer') -> 'MenuEntry': ...
    def isItemOp(self) -> bool: ...
    def getItemOp(self) -> int: ...
    def getItemId(self) -> int: ...
    def setItemId(self, itemId: int) -> 'MenuEntry': ...
    def getWidget(self) -> 'Widget': ...
    def getNpc(self) -> 'NPC': ...
    def getPlayer(self) -> 'Player': ...
    def getActor(self) -> 'Actor': ...
    def getSubMenu(self) -> 'Menu': ...
    def createSubMenu(self) -> 'Menu': ...
    def deleteSubMenu(self) -> None: ...
