import typing
from typing import Any, List, Dict, Set, Optional, Tuple, Iterable, Collection

class Menu:
    def __init__(self, java_instance: Any) -> None: ...
    def createMenuEntry(self, idx: int) -> 'MenuEntry': ...
    def getMenuEntries(self) -> typing.List['MenuEntry']: ...
    def setMenuEntries(self, entries: 'MenuEntry[]') -> None: ...
    def removeMenuEntry(self, entry: 'MenuEntry') -> None: ...
    def getMenuX(self) -> int: ...
    def getMenuY(self) -> int: ...
    def getMenuWidth(self) -> int: ...
    def getMenuHeight(self) -> int: ...
