import typing
from typing import Any, List, Dict, Set, Optional, Tuple, Iterable, Collection

class Node:
    def __init__(self, java_instance: Any) -> None: ...
    def getNext(self) -> 'Node': ...
    def getPrevious(self) -> 'Node': ...
    def getHash(self) -> int: ...
