import typing
from typing import Any, List, Dict, Set, Optional, Tuple, Iterable, Collection

class Scene:
    def __init__(self, java_instance: Any) -> None: ...
    def getTiles(self) -> typing.List['Tile[][]']: ...
    def getExtendedTiles(self) -> typing.List['Tile[][]']: ...
    def getExtendedTileSettings(self) -> typing.List['byte[][]']: ...
    def getDrawDistance(self) -> int: ...
    def setDrawDistance(self, drawDistance: int) -> None: ...
    def getWorldViewId(self) -> int: ...
    def getMinLevel(self) -> int: ...
    def setMinLevel(self, minLevel: int) -> None: ...
    def removeTile(self, tile: 'Tile') -> None: ...
    def removeGameObject(self, gameObject: 'GameObject') -> None: ...
    def buildRoofs(self) -> None: ...
    def getRoofs(self) -> typing.List['int[][]']: ...
    def setRoofRemovalMode(self, flags: int) -> None: ...
    def getRoofRemovalMode(self) -> int: ...
    def getUnderlayIds(self) -> typing.List['short[][]']: ...
    def getOverlayIds(self) -> typing.List['short[][]']: ...
    def getTileShapes(self) -> typing.List['byte[][]']: ...
    def getTileHeights(self) -> typing.List['int[][]']: ...
    def getBaseX(self) -> int: ...
    def getBaseY(self) -> int: ...
    def isInstance(self) -> bool: ...
    def getInstanceTemplateChunks(self) -> typing.List['int[][]']: ...
    def getMapRegions(self) -> typing.List[int]: ...
    def getOverrideAmount(self) -> 'byte': ...
    def getOverrideHue(self) -> 'byte': ...
    def getOverrideSaturation(self) -> 'byte': ...
    def getOverrideLuminance(self) -> 'byte': ...
