import typing
from typing import Any, List, Dict, Set, Optional, Tuple, Iterable, Collection

class Tile:
    def __init__(self, java_instance: Any) -> None: ...
    def getDecorativeObject(self) -> 'DecorativeObject': ...
    def getGameObjects(self) -> typing.List['GameObject']: ...
    def getItemLayer(self) -> 'ItemLayer': ...
    def getGroundObject(self) -> 'GroundObject': ...
    def setGroundObject(self, groundObject: 'GroundObject') -> None: ...
    def getWallObject(self) -> 'WallObject': ...
    def getSceneTilePaint(self) -> 'SceneTilePaint': ...
    def setSceneTilePaint(self, paint: 'SceneTilePaint') -> None: ...
    def getSceneTileModel(self) -> 'SceneTileModel': ...
    def setSceneTileModel(self, model: 'SceneTileModel') -> None: ...
    def getWorldLocation(self) -> 'WorldPoint': ...
    def getSceneLocation(self) -> 'Point': ...
    def getLocalLocation(self) -> 'LocalPoint': ...
    def getPlane(self) -> int: ...
    def getRenderLevel(self) -> int: ...
    def getGroundItems(self) -> typing.List['TileItem']: ...
    def getBridge(self) -> 'Tile': ...
