import typing
from typing import Any, List, Dict, Set, Optional, Tuple, Iterable, Collection

class TileObject:
    def __init__(self, java_instance: Any) -> None: ...
    def getHash(self) -> int: ...
    def getX(self) -> int: ...
    def getY(self) -> int: ...
    def getZ(self) -> int: ...
    def getPlane(self) -> int: ...
    def getWorldView(self) -> 'WorldView': ...
    def getId(self) -> int: ...
    def getWorldLocation(self) -> 'WorldPoint': ...
    def getLocalLocation(self) -> 'LocalPoint': ...
    def getCanvasLocation(self) -> 'Point': ...
    def getCanvasTilePoly(self) -> 'Polygon': ...
    def getCanvasTextLocation(self, graphics: 'Graphics2D', text: str, zOffset: int) -> 'Point': ...
    def getMinimapLocation(self) -> 'Point': ...
    def getClickbox(self) -> 'Shape': ...
    def getOpOverride(self, index: int) -> str: ...
    def isOpShown(self, index: int) -> bool: ...
