import typing
from typing import Any, List, Dict, Set, Optional, Tuple, Iterable, Collection

class World:
    def __init__(self, java_instance: Any) -> None: ...
    def getTypes(self) -> 'EnumSet': ...
    def setTypes(self, types: 'EnumSet') -> None: ...
    def getPlayerCount(self) -> int: ...
    def setPlayerCount(self, playerCount: int) -> None: ...
    def getLocation(self) -> int: ...
    def setLocation(self, location: int) -> None: ...
    def getIndex(self) -> int: ...
    def setIndex(self, index: int) -> None: ...
    def getId(self) -> int: ...
    def setId(self, id_: int) -> None: ...
    def getActivity(self) -> str: ...
    def setActivity(self, activity: str) -> None: ...
    def getAddress(self) -> str: ...
    def setAddress(self, address: str) -> None: ...
