import typing
from typing import Any, List, Dict, Set, Optional, Tuple, Iterable, Collection

class WorldView:
    def __init__(self, java_instance: Any) -> None: ...
    def getId(self) -> int: ...
    def isTopLevel(self) -> bool: ...
    def getScene(self) -> 'Scene': ...
    def players(self) -> 'Player>': ...
    def npcs(self) -> 'NPC>': ...
    def worldEntities(self) -> 'WorldEntity>': ...
    def worldViews(self) -> 'WorldView>': ...
    def getCollisionMaps(self) -> typing.List['CollisionData']: ...
    def getPlane(self) -> int: ...
    def getTileHeights(self) -> typing.List['int[][]']: ...
    def getTileSettings(self) -> typing.List['byte[][]']: ...
    def getSizeX(self) -> int: ...
    def getSizeY(self) -> int: ...
    def getBaseX(self) -> int: ...
    def getBaseY(self) -> int: ...
    def createProjectile(self, id_: int, plane: int, startX: int, startY: int, startZ: int, startCycle: int, endCycle: int, slope: int, startHeight: int, endHeight: int, target: 'Actor', targetX: int, targetY: int) -> 'Projectile': ...
    def getGraphicsObjects(self) -> 'Deque': ...
    def getSelectedSceneTile(self) -> 'Tile': ...
    def isInstance(self) -> bool: ...
    def getInstanceTemplateChunks(self) -> typing.List['int[][]']: ...
    def getMapRegions(self) -> typing.List[int]: ...
    def getXteaKeys(self) -> typing.List['int[]']: ...
    def contains(self, point: 'WorldPoint') -> bool: ...
    def getMainWorldProjection(self) -> 'Projection': ...
    def getCanvasProjection(self) -> 'Projection': ...
    def getYellowClickAction(self) -> int: ...
    def getTileHeight(self, x: int, y: int, maplevel: int) -> int: ...
